[project]
name = "final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "datasets>=3.1.0",
    "matplotlib>=3.7.5",
    "tensorboard>=2.14.0",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
]
